version: '3'
services:
  db: 
    image: "postgres:11"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: .
    ports:
      - "3000:3000"
    links:
      - "db:db"
    depends_on:
      - db
    environment: 
      - DB_CONNECTION_STRING=postgres://postgres@db:5432
